sudo: required

notifications:
  email: false

#Test only in travis branch for now
branches:
  only:
    - master

language: c

before_script:
  - sudo apt-add-repository -y 'deb http://archive.ubuntu.com/ubuntu trusty main universe multiverse restricted'
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update -y -qq
  - sudo apt-get install -y gcc-arm-none-eabi
  - sudo apt-get install -y cmake -qq

env:
  matrix:
  - BOARD='afc'        -VERSION='3.0' -RTM=''
  - BOARD='afc'        -VERSION='3.1' -RTM='rtm-8sfp'
  - BOARD='afc-timing' -VERSION=''    -RTM='rtm-8sfp'

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

script:
  - mkdir build_$BOARD_$VERSION && cd build_$BOARD_$VERSION && cmake ../ -DBOARD=$BOARD -DVERSION=$VERSION -DBOARD_RTM=$RTM -DCMAKE_BUILD_TYPE=Release && make

  # Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR/docs
  - bash deploy_docs.sh
